spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com/
          predicates:
            - Query=url,baidu
        - id: package_route
          uri: lb://logistics-package
          predicates:
            - Path=/api/pkg/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: order_route
          uri: lb://logistics-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: store_route
          uri: lb://logistics-store
          predicates:
            - Path=/api/store/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://logistics-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-admin/$\{segment}
        - id: logistics_host_route
          uri: http://localhost:8001/
          predicates:
            - Host=**.logistics.com,logistics.com