server:
  port: 9002

spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/logistics_package?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 991010
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: logistics-order
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
